# Generated by Django 3.2 on 2021-04-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('eggless', models.BooleanField(default=True)),
                ('flavour', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
