# Generated by Django 3.2 on 2021-04-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cake',
        ),
    ]
