# Generated by Django 3.2 on 2021-04-22 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cakeapp', '0002_delete_cake'),
    ]

    operations = [
        migrations.CreateModel(
            name='cake',
            fields=[
                ('cakeid', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.CharField(max_length=255)),
                ('eggless', models.BooleanField(default=True)),
                ('flavour', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
