# Generated by Django 3.2 on 2021-04-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0003_cake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cake',
        ),
    ]
