# Generated by Django 3.2 on 2021-04-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0005_cake_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='rating',
            new_name='ratings',
        ),
        migrations.AddField(
            model_name='cake',
            name='type',
            field=models.CharField(default='general', max_length=255),
        ),
    ]
