# Generated by Django 3.2 on 2021-04-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0006_auto_20210423_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='cake',
            name='type',
        ),
        migrations.AddField(
            model_name='cake',
            name='type',
            field=models.ManyToManyField(to='cakeapp.categories'),
        ),
    ]
