# Generated by Django 3.2 on 2021-04-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0007_auto_20210423_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cake',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
    ]
