# Generated by Django 3.2 on 2021-04-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0008_auto_20210423_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagemodel',
        ),
    ]
