# Generated by Django 3.2 on 2021-04-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0010_cake_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cakeapp.imagemodel'),
        ),
    ]
