# Generated by Django 3.2 on 2021-04-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0015_alter_cart_cakeid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
