# Generated by Django 3.2 on 2021-04-24 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0016_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakeid', models.IntegerField()),
                ('orderdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('weight', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
