# Generated by Django 3.2 on 2021-04-24 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0017_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('orderdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('price', models.IntegerField()),
                ('pending', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('mode', models.CharField(default='Cash', max_length=20)),
                ('cakes', models.ManyToManyField(to='cakeapp.cart')),
            ],
        ),
    ]
